# Generated by Django 5.1.4 on 2025-04-07 08:21

import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(default=shortener.models.generate_short_code, max_length=5, unique=True),
        ),
    ]
