# Generated by Django 5.2 on 2025-04-09 11:54

import django.db.models.deletion
import shortener.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_alter_shortenedurl_short_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="expires_at",
            field=models.DateTimeField(
                default=shortener.models.ShortenedURL.default_expiration
            ),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
